{{- if or (contains "jdnet" .chezmoi.fqdnHostname) (contains "wdx" .chezmoi.fqdnHostname) -}}
[".local/share/private-dotfiles"]
    type = "git-repo"
    url = "git@github.deere.com:l6ti0g0/private-dotfiles.git"
    refreshPeriod = "168h"
{{ end }}
