# AI-ASSISTED
import os
import paramiko

# Generate SSH key pair
private_key = paramiko.RSAKey.generate(2048)
public_key = private_key.get_base64()

# Save the private key to a file
private_key_file = os.path.expanduser(f'~/.ssh/id_{ssh_host}_rsa')
private_key.write_private_key_file(private_key_file)

# Save the public key to a file
public_key_file = os.path.expanduser('~/.ssh/id_{ssh_host}.pub')
with open(public_key_file, 'w') as f:
    f.write(f'ssh-rsa {public_key} autogenerated-key\n')

# Add public key to authorized_keys on SSH host
ssh_host = 'ssh_host@example.com'
ssh_port = 22
ssh_username = 'your_username'

client = paramiko.SSHClient()
client.load_system_host_keys()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())

client.connect(ssh_host, port=ssh_port, username=ssh_username)
sftp = client.open_sftp()
authorized_keys_path = f'/home/{ssh_username}/.ssh/authorized_keys'
sftp.put(public_key_file, authorized_keys_path)
sftp.close()

# Add private key to existing SSH host entry in SSH config
ssh_config_file = os.path.expanduser('~/.ssh/config')
with open(ssh_config_file, 'r') as f:
    ssh_config_lines = f.readlines()

with open(ssh_config_file, 'w') as f:
    found_host = False
    for line in ssh_config_lines:
        if line.strip().startswith(f'Host {ssh_host}'):
            f.write(line)
            f.write(f'    IdentityFile {private_key_file}\n')
            found_host = True
        else:
            f.write(line)

    if not found_host:
        f.write(f'\nHost {ssh_host}\n')
        f.write(f'    IdentityFile {private_key_file}\n')

client.close()

